type Project {
  id: ID
  name: String!
  tasks: [Task]
  order: Int
}

input NewProjectInput {
  name: String!
}

input UpdateProjectInput {
  id: ID!
  name: String!
}

input UpdateProjectOrderInput {
  id: ID!
  order: Int
}

extend type Query {
  project(id: ID!): Project!
  projects: [Project]!
}

extend type Mutation {
  newProject(input: NewProjectInput): Project!
  updateProject(input: UpdateProjectInput): Project!
  updateProjectsOrder(input: [UpdateProjectOrderInput]): [Project]
  removeProject(id: ID!): Project!
}
