type Task {
    id: ID
    name: String
    description: String
    project: Project
}

input NewTaskInput {
    project: ID!
    name: String!
    description: String
}

input TaskInput {
    id: ID!
}

extend type Query {
  task(input: TaskInput): Task!
  tasks: [Task]!
}

extend type Mutation {
  newTask(input: NewTaskInput): Task!
}